# Generated by Django 5.2.1 on 2025-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_names',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
            preserve_default=False,
        ),
    ]
