# Generated by Django 5.2.1 on 2025-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_booking_seat_names_booking_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_booked',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='booked_seats',
            field=models.JSONField(default=0),
        ),
    ]
