# Generated by Django 5.2.1 on 2025-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_booking_seats_booked_alter_show_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='booked_seats',
            field=models.JSONField(default=list),
        ),
    ]
