# Generated by Django 5.2.1 on 2025-06-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_show_booked_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
    ]
